name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ndpi-tile-cropper:$(date +%s) && docker build . --file parallel.Dockerfile --tag ndpi-tile-cropper-parallel:$(date +%s)
